In [61]:
import pandas as pd
import numpy as np


In [62]:
dataset = pd.read_csv('spam.csv')

In [63]:
dataset.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [64]:
dataset.isnull().sum()

Category    0
Message     0
dtype: int64

In [65]:
dataset.shape

(5572, 2)

In [66]:
dataset['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [68]:
dataset.replace({'Category': {'ham': 0, 'spam': 1}}, inplace=True)

In [69]:
dataset.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset['Message'], dataset['Category'], test_size=0.2, random_state=3)

In [71]:
X_train

3075                  Don know. I did't msg him recently.
1787    Do you know why god created gap between your f...
1614                         Thnx dude. u guys out 2nite?
4304                                      Yup i'm free...
3266    44 7732584351, Do you want a New Nokia 3510i c...
                              ...                        
789     5 Free Top Polyphonic Tones call 087018728737,...
968     What do u want when i come back?.a beautiful n...
1667    Guess who spent all last night phasing in and ...
3321    Eh sorry leh... I din c ur msg. Not sad alread...
1688    Free Top ringtone -sub to weekly ringtone-get ...
Name: Message, Length: 4457, dtype: object

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
train_vector = cv.fit_transform(X_train)

In [73]:
train_vector

<4457x7694 sparse matrix of type '<class 'numpy.int64'>'
	with 59126 stored elements in Compressed Sparse Row format>

In [74]:
X_train.shape

(4457,)

In [75]:
array = train_vector.toarray()
print(array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [76]:
cv.get_feature_names_out().shape

(7694,)

In [77]:
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()
classifier.fit(train_vector, y_train)

MultinomialNB()

In [78]:
from sklearn.metrics import accuracy_score

ytest_pred = classifier.predict(cv.transform(X_test))
print(accuracy_score(y_test, ytest_pred))

ytrain_pred = classifier.predict(cv.transform(X_train))
print(accuracy_score(y_train, ytrain_pred))

0.9901345291479821
0.9928202827013687


In [79]:
from sklearn.metrics import classification_report

ytest_pred = classifier.predict(cv.transform(X_test))
print(classification_report(y_test, ytest_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.99      0.94      0.96       155

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [80]:
import pickle
# Save model to file
with open('model.pkl', 'wb') as file:
    pickle.dump(classifier, file)

# Load model from file
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

In [81]:
ytest_pred = loaded_model.predict(cv.transform(X_test))
print(classification_report(y_test, ytest_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.99      0.94      0.96       155

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [83]:
# Save the CountVectorizer object to a file
with open('count_vectorizer.pkl', 'wb') as file:
    pickle.dump(cv, file)

In [86]:
# Load the CountVectorizer object from the file
with open('count_vectorizer.pkl', 'rb') as file:
    loaded_cv = pickle.load(file)

In [87]:
ytest_pred = loaded_model.predict(loaded_cv.transform(X_test))
print(classification_report(y_test, ytest_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       960
           1       0.99      0.94      0.96       155

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [88]:
messages = ["Congratulations! You have won a free cruise!", "Hey, what are you up to tonight?"]
new_messages = loaded_cv.transform(messages)
predictions = loaded_model.predict(new_messages)
print(predictions)

[1 0]
